In [3]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')

In [6]:
#행정구역별 인구수
df  = pd.read_excel('행정구역_202401.xlsx', skiprows=1)
df.head(2)

  행정구역(시군구)별  총인구수 (명)  남자인구수 (명)  여자인구수 (명)
0         전국  51313912   25558944   25754968
1      서울특별시   9384325    4538354    4845971

In [8]:
df1 = df.copy()
df1.columns = ['행정구역2', '총인구수', '남자인구수', '여자인구수']
df1['행정구역1'] = ''
df1.head(2)

   행정구역2      총인구수     남자인구수     여자인구수 행정구역1
0     전국  51313912  25558944  25754968
1  서울특별시   9384325   4538354   4845971

In [ ]:
df2 = df1.copy()
cols = list(df1.columns)
df2 = df1[[cols[-1]] + cols[0:-1]] #df2 = df1[['행정구역1', '행정구역2'...]]
df2.head(2)

  행정구역1  행정구역2      총인구수     남자인구수     여자인구수
0           전국  51313912  25558944  25754968
1        서울특별시   9384325   4538354   4845971

In [15]:
sidos = ['특별시', '광역시', '자치시', '경기도', '남도', '북도', '자치도']
for i in range(1, len(df2)):
    for sido in sidos:
        if sido in df2.loc[i, '행정구역2']:
            df2.loc[i, '행정구역1'] = df2.loc[i, '행정구역2']
            df2.loc[i, '행정구역2'] = '소계'
df2

       행정구역1    행정구역2      총인구수     남자인구수     여자인구수
0                  전국  51313912  25558944  25754968
1      서울특별시       소계   9384325   4538354   4845971
2              　　　종로구    139378     67240     72138
3               　　　중구    121322     58651     62671
4              　　　용산구    212175    101793    110382
..       ...      ...       ...       ...       ...
288            　　　거창군     59909     29480     30429
289            　　　합천군     41096     20094     21002
290  제주특별자치도       소계    674353    337578    336775
291            　　　제주시    490888    245197    245691
292           　　　서귀포시    183465     92381     91084

[293 rows x 5 columns]

In [18]:
for i in range(2, len(df2)):
    if df2.loc[i, '행정구역1'] == '':
        df2.loc[i, '행정구역1'] = df2.loc[i-1, '행정구역1']

df2.loc[0, '행정구역1'] = '전국'
df2.loc[0, '행정구역2'] = '합계'
df2

       행정구역1    행정구역2      총인구수     남자인구수     여자인구수
0         전국       합계  51313912  25558944  25754968
1      서울특별시       소계   9384325   4538354   4845971
2      서울특별시   　　　종로구    139378     67240     72138
3      서울특별시    　　　중구    121322     58651     62671
4      서울특별시   　　　용산구    212175    101793    110382
..       ...      ...       ...       ...       ...
288     경상남도   　　　거창군     59909     29480     30429
289     경상남도   　　　합천군     41096     20094     21002
290  제주특별자치도       소계    674353    337578    336775
291  제주특별자치도   　　　제주시    490888    245197    245691
292  제주특별자치도  　　　서귀포시    183465     92381     91084

[293 rows x 5 columns]

In [19]:
df2.to_csv('행정구역별인구수.csv')

In [21]:
df3 = pd.read_csv('행정구역별인구수.csv', index_col=0)
df3.head()

   행정구역1   행정구역2      총인구수     남자인구수     여자인구수
0     전국      합계  51313912  25558944  25754968
1  서울특별시      소계   9384325   4538354   4845971
2  서울특별시  　　　종로구    139378     67240     72138
3  서울특별시   　　　중구    121322     58651     62671
4  서울특별시  　　　용산구    212175    101793    110382